### PR TITLE
proposed jsdoc requirement

### PR DESCRIPTION
**Pull request by kirstein**
All js should have valid jsDoc

### CODE REVIEW

**Comment by mklopets** [comment]
I actually think JSDoc blocks might be an unnecessary overkill in some cases.

**Comment by martinraag** [comment]
I think at the very least requiring exports of a module to have valid jsdoc to be a good idea. AFAIK integrations team already requires this on their projects. Want to weigh in @taavirehemagi @martr ?

**Comment by mklopets** [comment]
@martinraag Looks like the require-jsdoc rule is kind of broken, especially for using it for module.exports (see https://github.com/eslint/eslint/issues/5867). It doesn't have support for just requiring JSDoc for exports, either – it can just be turned on/of for *all* classes, class methods and/or functions.

**Comment by henrinormak** [comment]
This PR is quite old, any change to your dislike of the idea, @mklopets?

**Pull request closed without merging**
